### ISSUE TITLE
파일 뻘짓

### ISSUE THREAD

**Issue by highright1234** [devproje/project-mirror#1]
/v1/login 접근을 통해서 로그인 시도를 할때 `auth/mod.go`에 `get()`을 하며 JSON 열었다 닫았다 해서  
악용해서 Login쪽에만 DDoS 보내면 IO 뻘짓 가능한듯  
이건 다른거긴 한데 /static/ 열수 있어서 index.html 열수있음  
(Go 잘 몰라서 틀릴수도 있음)

**Comment by devproje** [comment]
check
